using System.ComponentModel.DataAnnotations;
using Microsoft.EntityFrameworkCore;

namespace lab2.Data.Model
{
    /// <summary>
    /// Base user entity for all user types (Student, Teacher).
    /// Contains common properties shared across all user types.
    /// </summary>
    [PrimaryKey(nameof(Id))]
    public class MyUser
    {
        /// <summary>
        /// Unique identifier for the user. Auto-generated by database.
        /// </summary>
        public int Id { get; set; }

        /// <summary>
        /// Display name of the user. Maximum 50 characters.
        /// </summary>
        [StringLength(50)]
        [Display(Name = "User Name")]
        public string Name { get; set; } = "";

        /// <summary>
        /// Birth date of the user. Stored as date only (no time).
        /// </summary>
        [Display(Name = "Birth Date")]
        [DataType(DataType.Date)]
        public DateTime BirthDate { get; set; }

        /// <summary>
        /// Cell phone number. Maximum 17 characters for international format.
        /// </summary>
        [StringLength(17)]
        [DataType(DataType.PhoneNumber)]
        public string CellPhone { get; set; } = "";

        /// <summary>
        /// External user ID from identity provider. Nullable.
        /// </summary>
        [StringLength(50)]
        public string? UserID = null;
    }
}
